"""Ground-up agent system scaffold generator."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from .plan import CyclePlan


def write_scaffold(root: Path, plan: CyclePlan) -> dict[str, Any]:
    root.mkdir(parents=True, exist_ok=True)
    files: dict[str, str] = {}

    files["IDENTITY.md"] = (
        f"# {plan.target}\n\n"
        f"**Identity:** {plan.identity}\n"
        f"**Mode:** {plan.mode}\n"
        f"**Problem:** {plan.problem}\n\n"
        "Cycle: Discover → Frame → Build → Integrate → Evaluate → Prove → Deploy\n"
    )
    files["PLAN.yaml"] = _plan_yaml(plan)
    files["src/agent/__init__.py"] = '"""Agent package scaffold."""\n'
    files["src/agent/orchestrator.py"] = _orchestrator_stub(plan)
    files["src/agent/policy.py"] = _policy_stub()
    files["src/agent/memory_port.py"] = _memory_port_stub()
    files["tests/test_scaffold_smoke.py"] = _smoke_test(plan.target)
    files["README.md"] = (
        f"# {plan.target}\n\nGenerated by Forward-Deployed-Agentic-Powerhouse.\n\n"
        f"Identity: {plan.identity}\nMode: {plan.mode}\n"
    )

    written = []
    for rel, content in files.items():
        path = root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        written.append(str(path))

    return {"root": str(root), "files": written, "count": len(written)}


def _plan_yaml(plan: CyclePlan) -> str:
    lines = [
        f"identity: {plan.identity!r}",
        f"mode: {plan.mode}",
        f"target: {plan.target}",
        f"problem: {plan.problem!r}",
        "skill_targets:",
    ]
    for s in plan.skill_targets:
        lines.append(f"  - {s}")
    lines.append(f"genius_role: {plan.genius_role}")
    lines.append("genius_outcomes:")
    for o in plan.genius_outcomes:
        lines.append(f"  - {o!r}")
    lines.append("memory_tiers:")
    for t in plan.memory_tiers:
        lines.append(f"  - {t}")
    lines.append("constraints:")
    for c in plan.constraints:
        lines.append(f"  - {c}")
    return "\n".join(lines) + "\n"


def _orchestrator_stub(plan: CyclePlan) -> str:
    return f'''"""Orchestrator stub — {plan.identity}."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass
class Task:
    id: str
    deps: list[str] = field(default_factory=list)
    status: str = "pending"


@dataclass
class Orchestrator:
    """Dependency-aware task runner (scaffold)."""

    tasks: dict[str, Task] = field(default_factory=dict)

    def add(self, task_id: str, deps: list[str] | None = None) -> None:
        self.tasks[task_id] = Task(id=task_id, deps=list(deps or []))

    def ready(self) -> list[str]:
        done = {{t for t, v in self.tasks.items() if v.status == "done"}}
        out = []
        for tid, task in self.tasks.items():
            if task.status != "pending":
                continue
            if all(d in done for d in task.deps):
                out.append(tid)
        return sorted(out)

    def complete(self, task_id: str) -> None:
        if task_id not in self.tasks:
            raise KeyError(task_id)
        self.tasks[task_id].status = "done"

    def snapshot(self) -> dict[str, Any]:
        return {{k: v.status for k, v in self.tasks.items()}}
'''


def _policy_stub() -> str:
    return '''"""Tool-call policy stub — ALLOW / CONFIRM / DENY."""

from __future__ import annotations

from enum import Enum


class Disposition(str, Enum):
    ALLOW = "ALLOW"
    CONFIRM = "CONFIRM"
    DENY = "DENY"


HIGH_RISK = ("rm", "delete", "drop", "force", "sudo")


def review(command: str) -> Disposition:
    lowered = command.lower()
    if any(tok in lowered for tok in HIGH_RISK):
        return Disposition.CONFIRM
    if "format" in lowered or "mkfs" in lowered:
        return Disposition.DENY
    return Disposition.ALLOW
'''


def _memory_port_stub() -> str:
    return '''"""Memory port — bridge to Aspen / Pro-Memory when configured."""

from __future__ import annotations

from typing import Any


class MemoryPort:
    """In-process working memory; swap for estate memory when path available."""

    def __init__(self) -> None:
        self._store: dict[str, Any] = {}

    def put(self, key: str, value: Any) -> None:
        self._store[key] = value

    def get(self, key: str, default: Any = None) -> Any:
        return self._store.get(key, default)

    def keys(self) -> list[str]:
        return sorted(self._store)
'''


def _smoke_test(target: str) -> str:
    return f'''"""Smoke test for scaffold {target}."""

from agent.orchestrator import Orchestrator
from agent.policy import Disposition, review


def test_orchestrator_deps():
    o = Orchestrator()
    o.add("a")
    o.add("b", deps=["a"])
    assert o.ready() == ["a"]
    o.complete("a")
    assert o.ready() == ["b"]


def test_policy_allow():
    assert review("echo hello") == Disposition.ALLOW


def test_policy_confirm():
    assert review("rm -rf /tmp/x") == Disposition.CONFIRM
'''
